### ISSUE TITLE
Can't disable STARTTLS

### ISSUE THREAD

**Issue by UksusoFF** [DominikSerafin/maildev#5]
I'm trying to disable STARTTLS extension for solve this: https://github.com/maildev/maildev/issues/274#issuecomment-564542032
But container stops with:
```
/home/node/lib/mailserver.js:202
  return extensions.reduce(function (options, extension) {
                    ^

TypeError: extensions.reduce is not a function
    at getHideExtensionOptions (/home/node/lib/mailserver.js:202:21)
    at Object.mailServer.create (/home/node/lib/mailserver.js:167:32)
    at new module.exports (/home/node/index.js:25:14)
    at Object.<anonymous> (/home/node/bin/maildev:9:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

docker-compose:
```
  maildev:
    container_name: flikto_mail
    image: dominikserafin/maildev
    environment:
      MAILDEV_HIDE_EXTENSIONS: STARTTLS
    ports:
      - 1025:1025
      - 1080:1080
```
