### ISSUE TITLE
How to use the Docker image

### ISSUE THREAD

**Issue by gh640** [DominikSerafin/maildev#6]
The Docker image exposes `1080` for web and `1025` for smtp. It would help to explain how to use the image in README like:

```bash
$ docker run -p 1080:1080 -p 1025:1025 dominikserafin/maildev:latest
```

```yaml
version: "3"

services:
  mail:
    image: dominikserafin/maildev:latest
    ports:
      - "1080:1080"
```
